### ISSUE TITLE
ReferenceError: DevExpress is not defined

### ISSUE THREAD

**Issue by skysoftrepo** [DevExpress/dashboard-extension-online-map-item#3]
I'm trying to implement the google map on web dashboard and followed the instructions described in installation steps. 
URL: https://github.com/DevExpress/dashboard-extension-online-map-item

But just after adding the reference  of "online-map-extension.min.js" on my view page, dashboard stops appearing. And gives two below errors : 

1. ReferenceError: DevExpress is not defined
2. TypeError: CustomItems.OnlineMapItemExtension is not a constructor 

Please help me out here.

Thanks

**Comment by kaatula** [comment]
Hi,
 
It looks like you put a link to the ```online-map-extension.min.js``` script above the link for the DevExpress client libraries. 
 
The main libraries are linked in different ways for different platforms:
- ```@Html.DevExpress().Scripts()``` for ASP.NET Core
- ```@Html.DevExpress().GetScripts( ... )``` for ASP.NET MVC / WebForms
- ```<script src="bundle/dx.dashboard-control.bundle.js"></script>``` for a client approach
 
Make sure that online-map-extension is placed below these lines.
 
If the problem is not solved, [create a ticket](https://www.devexpress.com/Support/Center/Question/Create) in the DevExpress Support Center and add info about your platform and your page markup.
 
Andrey
